import { AlertTriangle, CheckCircle2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ComponentStatusBadge } from "@/components/xai/xai-status-badge";
import type {
  ExplanationComponentErrors,
  ExplanationComponentName,
  ExplanationError,
} from "@/types/api";

const TEMPORAL_ANALYSIS_LIMITATION =
  "Candidate regions are derived from attention-rollout tensors captured during the XLS-R transformer's original classification pass. They indicate where the model concentrated attention, not verified spoof artifacts or causal proof.";

const SEMANTIC_ANALYSIS_LIMITATION =
  "Semantic evidence is generated by an independent acoustic model from sliding-window SHAP attributions. It is auxiliary evidence and does not directly explain or change the multi-branch classifier's decision.";

const REPORT_LIMITATION = "Decision support evidence only. Human review required.";

/**
 * Backend-reported warnings and per-component errors.
 *
 * Component errors are already sanitised server-side into a fixed
 * `{code, message}` vocabulary — no traceback, filesystem path, or raw
 * exception reaches this component. The message is rendered as plain text.
 */
export function WarningsPanel({
  warnings,
  componentErrors,
  runError,
  limitationFor = "temporal",
}: {
  warnings: string[];
  componentErrors: ExplanationComponentErrors;
  runError?: ExplanationError | null;
  limitationFor?: "temporal" | "semantic" | "report" | "both" | "none";
}) {
  const candidates: Array<[ExplanationComponentName, ExplanationError | null | undefined]> = [
    ["temporal", componentErrors.temporal],
    ["semantic", componentErrors.semantic],
    ["report", componentErrors.report],
  ];
  const errorEntries = candidates.filter(
    (entry): entry is [ExplanationComponentName, ExplanationError] => Boolean(entry[1]),
  );

  const hasContent = warnings.length > 0 || errorEntries.length > 0 || Boolean(runError);
  const limitations =
    limitationFor === "none"
      ? []
      : limitationFor === "both"
        ? [TEMPORAL_ANALYSIS_LIMITATION, SEMANTIC_ANALYSIS_LIMITATION]
      : limitationFor === "semantic"
        ? [SEMANTIC_ANALYSIS_LIMITATION]
        : limitationFor === "report"
          ? [REPORT_LIMITATION]
          : [TEMPORAL_ANALYSIS_LIMITATION];

  return (
    <Card>
      <CardHeader>
        <CardTitle>Warnings and limitations</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {!hasContent ? (
          <p className="flex items-center gap-2 text-sm text-muted-foreground">
            <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
            No warnings were reported for this run.
          </p>
        ) : null}

        {limitations.map((limitation) => (
          <p key={limitation} className="flex gap-2 text-sm text-muted-foreground">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
            <span>{limitation}</span>
          </p>
        ))}

        {runError ? (
          <div className="rounded-md border border-destructive/40 bg-destructive/5 p-3">
            <p className="flex items-center gap-2 text-sm font-medium">
              <AlertTriangle className="h-4 w-4" aria-hidden="true" />
              Run error
            </p>
            <p className="mt-1 text-sm">{runError.message}</p>
            <p className="mt-1 font-mono text-xs text-muted-foreground">{runError.code}</p>
          </div>
        ) : null}

        {errorEntries.length > 0 ? (
          <div className="space-y-2">
            <h4 className="text-sm font-semibold">Component errors</h4>
            {errorEntries.map(([component, error]) => (
              <div key={component} className="rounded-md border p-3">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <span className="text-sm font-medium capitalize">{component}</span>
                  <ComponentStatusBadge status="failed" />
                </div>
                <p className="mt-1 text-sm">{error.message}</p>
                <p className="mt-1 font-mono text-xs text-muted-foreground">{error.code}</p>
              </div>
            ))}
          </div>
        ) : null}

        {warnings.length > 0 ? (
          <div>
            <h4 className="text-sm font-semibold">Reported warnings ({warnings.length})</h4>
            <ul className="mt-2 space-y-2">
              {warnings.map((warning) => (
                <li key={warning} className="flex gap-2 rounded-md border p-3 text-sm">
                  <AlertTriangle
                    className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground"
                    aria-hidden="true"
                  />
                  <span>{warning}</span>
                </li>
              ))}
            </ul>
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}
